Feature/use typeconversion in schemas
jansigi/crystal-map pull request #3
Opened 2024-07-12 14:16 UTC by jansigi

2024-07-17 05:59 UTC, cyrillhalter requested changes

2024-07-17 05:59 UTC, cyrillhalter commented on crystal-map-processor/src/test/resources/ExpectedSchema.txt
Please also add the new use case to the expected schema

2024-07-17 07:49 UTC, jansigi commented on crystal-map-processor/src/test/resources/ExpectedSchema.txt
done

2024-08-07 17:27 UTC, pgruntz approved these changes

2024-08-07 17:27 UTC, pgruntz commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
Why don't you use _getOuterPropertyType()_?

2024-08-07 17:27 UTC, pgruntz commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
What do you mean by **outer**Type?

2024-08-07 17:27 UTC, pgruntz commented on crystal-map-api/src/main/java/com/schwarz/crystalapi/schema/CMType.kt
> +    val typeConverter: ITypeConverter<KotlinType, MapType>,
I find the order of the arguments strange, shouldn't typeConverted be the last argument?

2024-08-07 17:27 UTC, pgruntz commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +                buildConverterFieldProperty(fieldObject, propertyType, fieldName)
Again, I feel like the order should be `buildConverterFieldProperty(fieldObject, fieldName, propertyType)`

2024-08-07 17:35 UTC, pgruntz commented on crystal-map-api/src/main/java/com/schwarz/crystalapi/schema/CMType.kt
> +class CMConverterField<KotlinType, MapType>(
Regardin naming, shoudn't this be the real _CMField_ since this si what we expect usually? And the old CMField something like _CMBaseField_? And do we really need this inheritance semantically. Doesn't a field with a nullable typeConverter make more sense?

2024-08-08 10:39 UTC, jansigi commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
Because the `getOuterPropertyType` works only for the normal CMTypes.

2024-08-08 10:43 UTC, jansigi commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
`outerType` it the Type that uses a Generic (or multiple). So for example, when you have this class: `class Exam<T>` then the `Exam` is the outerType and `T` would be the inner type

2024-08-08 10:50 UTC, jansigi commented on crystal-map-api/src/main/java/com/schwarz/crystalapi/schema/CMType.kt
> +    val typeConverter: ITypeConverter<KotlinType, MapType>,
yes you are correct.

2024-08-08 10:56 UTC, jansigi commented on crystal-map-api/src/main/java/com/schwarz/crystalapi/schema/CMType.kt
> +class CMConverterField<KotlinType, MapType>(
We still normaly expect the "normal" CMField. The CMFIeld is just a Field with the Json DataTypes and the Converters are used for types, which don't have a own Json Type. I also think that a nullable TypeConverter dosn't really make sense, because we would still need two Generics, which we wouldn't have if it doesn't have a converter.

2024-08-08 15:51 UTC, pgruntz commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
Why?

2024-08-08 15:56 UTC, pgruntz commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
It's a bit strange that you are using `outerType` here but no `innerType`.

2024-08-08 15:59 UTC, pgruntz commented on crystal-map-api/src/main/java/com/schwarz/crystalapi/schema/CMType.kt
> +class CMConverterField<KotlinType, MapType>(
What about _CMJsonField_ and _CMField_?

2024-08-09 06:46 UTC, jansigi commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
I saw, that it could be extracted with the others ("getOUterPropertyType") and I changed it now.

2024-08-09 06:48 UTC, jansigi commented on crystal-map-processor/src/main/java/com/schwarz/crystalprocessor/generation/model/SchemaGeneration.kt
> +        val outerType = if (fieldObject.isIterable) {
In this funciton we have two innerclasses, which are the `propertyType.domainClassTypeName`, `propertyType.mapClassTypeName`

2024-08-09 07:56 UTC, jansigi commented on crystal-map-api/src/main/java/com/schwarz/crystalapi/schema/CMType.kt
> +class CMConverterField<KotlinType, MapType>(
done

2024-08-13 09:29 UTC, closed without merging